<#
.SYNOPSIS
    Prepare a Hyper-V VM as a CafresoAI gold image for workspace streaming.

.DESCRIPTION
    Installs and configures Sunshine (LizardByte), Virtual Display Driver,
    and auto-login so the VM can be cloned and streamed without user
    interaction. Run this INSIDE the VM (not on the host).

    After running, create a checkpoint on the host:
      Checkpoint-VM -Name "Win11-Dev-Gold" -SnapshotName "cafreso-gold-v1"

.NOTES
    Requires: Windows 11 Pro/Enterprise, Administrator privileges
    Host:     Windows Server 2025 Datacenter with Hyper-V + GPU-P
#>

#Requires -RunAsAdministrator
$ErrorActionPreference = 'Stop'

$SunshineVersion  = 'v2025.130.152647'
$SunshineUrl      = "https://github.com/LizardByte/Sunshine/releases/download/$SunshineVersion/sunshine-windows-installer.exe"
$VddUrl           = 'https://github.com/itsmikethetech/Virtual-Display-Driver/releases/latest/download/VirtualDisplayDriver.zip'
$WorkDir          = "$env:TEMP\cafreso-gold"

Write-Host '=== CafresoAI Gold Image Preparation ===' -ForegroundColor Cyan

# ── 1. Create work directory ────────────────────────────────────────────────
if (-not (Test-Path $WorkDir)) { New-Item -ItemType Directory -Path $WorkDir -Force | Out-Null }

# ── 2. Install Sunshine ─────────────────────────────────────────────────────
Write-Host "`n[1/6] Installing Sunshine ($SunshineVersion)..." -ForegroundColor Yellow

$sunshineExe = "$WorkDir\sunshine-installer.exe"
if (-not (Test-Path $sunshineExe)) {
    Write-Host "  Downloading from GitHub..."
    Invoke-WebRequest -Uri $SunshineUrl -OutFile $sunshineExe -UseBasicParsing
}

Write-Host "  Running installer (silent)..."
Start-Process -FilePath $sunshineExe -ArgumentList '/S' -Wait -NoNewWindow
Start-Sleep -Seconds 5

# Verify installation
$sunshinePath = Get-ChildItem "$env:ProgramFiles\Sunshine" -Recurse -Filter 'sunshine.exe' -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $sunshinePath) {
    Write-Warning "Sunshine not found at expected path. Check installer output."
} else {
    Write-Host "  Sunshine installed: $($sunshinePath.FullName)" -ForegroundColor Green
}

# ── 3. Install Virtual Display Driver ──────────────────────────────────────
Write-Host "`n[2/6] Installing Virtual Display Driver..." -ForegroundColor Yellow

$vddZip = "$WorkDir\VirtualDisplayDriver.zip"
$vddDir = "$WorkDir\VDD"
if (-not (Test-Path $vddZip)) {
    Invoke-WebRequest -Uri $VddUrl -OutFile $vddZip -UseBasicParsing
}
Expand-Archive -Path $vddZip -DestinationPath $vddDir -Force

# Install the driver (run the installer script if present)
$vddInstaller = Get-ChildItem $vddDir -Recurse -Filter '*.bat' | Select-Object -First 1
if ($vddInstaller) {
    Write-Host "  Running VDD installer: $($vddInstaller.Name)"
    Start-Process -FilePath 'cmd.exe' -ArgumentList "/c `"$($vddInstaller.FullName)`"" -Wait -NoNewWindow
} else {
    Write-Host "  Manual VDD install may be needed - no .bat found in archive" -ForegroundColor Yellow
}

# ── 4. Configure Sunshine for headless streaming ───────────────────────────
Write-Host "`n[3/6] Configuring Sunshine for CafresoAI..." -ForegroundColor Yellow

$sunshineConf = "$env:ProgramFiles\Sunshine\config\sunshine.conf"
$sunshineDir  = Split-Path $sunshineConf -Parent
if (-not (Test-Path $sunshineDir)) { New-Item -ItemType Directory -Path $sunshineDir -Force | Out-Null }

# Sunshine configuration for headless, PIN-less streaming
$confContent = @"
# CafresoAI Sunshine Configuration
# Auto-generated by Prepare-GoldImage.ps1

# Network
port = 47989
address_family = both

# Streaming
encoder = nvenc
min_fps_factor = 1

# Authentication - PIN-less for automated pairing
# The gateway handles auth via Internet Identity; Sunshine trusts LAN clients
pin = ""

# Virtual display (use VDD instead of physical monitor)
output_name = 1

# Logging
min_log_level = info
"@

Set-Content -Path $sunshineConf -Value $confContent -Encoding UTF8
Write-Host "  Config written: $sunshineConf" -ForegroundColor Green

# ── 5. Configure auto-login ───────────────────────────────────────────────
Write-Host "`n[4/6] Configuring auto-login..." -ForegroundColor Yellow

# Set registry keys for automatic logon (the VM needs to boot into desktop
# without a password prompt so Sunshine can capture the desktop)
$regPath = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
Set-ItemProperty -Path $regPath -Name 'AutoAdminLogon' -Value '1' -Type String
Set-ItemProperty -Path $regPath -Name 'DefaultUserName' -Value 'CafresoUser' -Type String
# DefaultPassword should be set by the admin
Write-Host "  Auto-login enabled for 'CafresoUser'" -ForegroundColor Green
Write-Host "  NOTE: Set DefaultPassword in the registry before checkpointing." -ForegroundColor Yellow

# ── 6. Register Sunshine as a service ─────────────────────────────────────
Write-Host "`n[5/6] Registering Sunshine as a Windows service..." -ForegroundColor Yellow

$sunshineExePath = if ($sunshinePath) { $sunshinePath.FullName } else { $null }
if ($sunshineExePath) {
    # Create a scheduled task that starts Sunshine at logon
    $action  = New-ScheduledTaskAction -Execute $sunshineExePath
    $trigger = New-ScheduledTaskTrigger -AtLogOn
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
    Register-ScheduledTask -TaskName 'CafresoAI-Sunshine' -Action $action -Trigger $trigger -Settings $settings -User 'CafresoUser' -RunLevel Highest -Force
    Write-Host "  Scheduled task 'CafresoAI-Sunshine' registered" -ForegroundColor Green
} else {
    Write-Host "  Skipped - Sunshine path unknown" -ForegroundColor Yellow
}

# ── 7. Disable unnecessary services for performance ───────────────────────
Write-Host "`n[6/6] Optimizing VM for streaming..." -ForegroundColor Yellow

# Disable Windows Update service (gold image shouldn't auto-update)
Stop-Service -Name wuauserv -Force -ErrorAction SilentlyContinue
Set-Service -Name wuauserv -StartupType Disabled -ErrorAction SilentlyContinue

# Disable Search indexer
Stop-Service -Name WSearch -Force -ErrorAction SilentlyContinue
Set-Service -Name WSearch -StartupType Disabled -ErrorAction SilentlyContinue

# Disable Superfetch/SysMain
Stop-Service -Name SysMain -Force -ErrorAction SilentlyContinue
Set-Service -Name SysMain -StartupType Disabled -ErrorAction SilentlyContinue

Write-Host "  Disabled: Windows Update, Search, SysMain" -ForegroundColor Green

# ── Done ──────────────────────────────────────────────────────────────────
Write-Host "`n=== Gold Image Preparation Complete ===" -ForegroundColor Cyan
Write-Host @"

Next steps:
  1. Set the auto-login password:
       Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'DefaultPassword' -Value 'YOUR_PASSWORD'

  2. Reboot the VM and verify:
       - Auto-login works (boots to desktop)
       - Sunshine starts automatically
       - Virtual display is active
       - GPU-P partition is assigned (on host: Add-VMGpuPartitionAdapter)

  3. On the Hyper-V HOST, create the gold checkpoint:
       Checkpoint-VM -Name 'YOUR_VM_NAME' -SnapshotName 'cafreso-gold-v1'

  4. Update oci-fleet/workspaces.json with the vm_template name.
"@
