#!/usr/bin/env python3
"""Assemble the `hq-ui/` asset-canister build dir for the CafresoHQ frontend.

The HQ app (hq.html + built UI bundle + styles.css + assets + sw.js + manifest) is
normally served by serve.py. For the frontend/backend split it's served from an ICP
asset canister instead (1-min `dfx deploy`, fleet-wide, no image rebuild).

The UI is no longer raw JSX transpiled in-browser. This script first runs the Node
build (scripts/build_ui_bundle.mjs) to produce dist-ui/ (vendor globals + content-
hashed, pre-transformed JSX), then copies ONLY the UI files into `hq-ui/` (so
serve.py, oci-fleet, node_modules, etc. never ship to the canister), bakes the
<!--HQ_SCRIPTS--> placeholder in hq.html from the build manifest, and writes the
canister's `.ic-assets.json5` (cache + CSP). It is the `build` step of the
`cafresohq_ui` canister in dfx.json.

Cross-platform (Windows/WSL/Linux). Idempotent — wipes and rebuilds.
"""
import os
import stat
import shutil
import subprocess

import ui_manifest  # sibling module in scripts/ (on sys.path when run as a script)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, 'hq-ui')
DIST = os.path.join(ROOT, 'dist-ui')

# Files copied verbatim from the repo root. The JSX is NOT shipped — the built,
# hashed bundle in dist-ui/bundle/ replaces it (see _copy_bundle).
FILES = ['hq.html', 'styles.css', 'sw.js', 'manifest.webmanifest', 'graph-viewer.html']
DIRS = ['assets']

# Canister upload config. The HQ app self-hosts React/xterm and ships pre-transformed
# JSX (no unpkg, no in-browser Babel → no 'wasm-unsafe-eval'). 'unsafe-inline' stays
# for the inline boot/splash script + style block in hq.html. Fonts from Google.
# connect-src is permissive for https/wss so the API origin (Caddy/container) and ws
# endpoints work; tighten to your exact API origin in production if desired.
IC_ASSETS = r'''// Auto-generated by scripts/build_hq_ui.py — do not edit by hand.
[
  {
    match: "**/*",
    headers: {
      "Cache-Control": "public, max-age=600",
      "X-Content-Type-Options": "nosniff",
      "Referrer-Policy": "strict-origin-when-cross-origin",
      "Content-Security-Policy": "default-src 'self'; img-src 'self' data: blob: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https: wss: http://localhost:* http://127.0.0.1:* ws://localhost:* ws://127.0.0.1:*; frame-src 'self' https://identity.ic0.app https://*.cafreso.com; frame-ancestors 'self' https://*.cafreso.com; form-action 'self';"
    }
  },
  {
    match: "bundle/**",
    headers: { "Cache-Control": "public, max-age=31536000, immutable" }
  },
  {
    match: "hq.html",
    headers: { "Cache-Control": "public, max-age=0, must-revalidate" }
  },
  {
    match: "sw.js",
    headers: { "Cache-Control": "public, max-age=0, must-revalidate" }
  }
]
'''


def _force_rmtree(path):
    """rmtree that survives Windows read-only attributes (copy2 preserves the
    read-only bit from source assets, which makes a plain rmtree fail WinError 5)."""
    def _on_err(func, p, _exc):
        try:
            os.chmod(p, stat.S_IWRITE)
            func(p)
        except Exception:
            pass
    if not os.path.isdir(path):
        return
    try:                                   # Python 3.12+: onexc
        shutil.rmtree(path, onexc=_on_err)
    except TypeError:                      # older: onerror
        shutil.rmtree(path, onerror=_on_err)


def _run_node_build():
    """Run the esbuild UI build (scripts/build_ui_bundle.mjs) via npm. Installs deps
    first if node_modules is absent. Cross-platform npm resolution."""
    is_win = (os.name == 'nt')
    npm = (shutil.which('npm.cmd') if is_win else None) or shutil.which('npm')
    if not npm:
        raise SystemExit('[build-hq-ui] npm not found on PATH. Install Node.js >=18 '
                         'to build the HQ UI bundle.')

    def run(args):
        if is_win:
            subprocess.run('"%s" %s' % (npm, ' '.join(args)), cwd=ROOT, check=True, shell=True)
        else:
            subprocess.run([npm] + args, cwd=ROOT, check=True)

    if not os.path.isdir(os.path.join(ROOT, 'node_modules')):
        print('[build-hq-ui] installing npm deps…')
        run(['ci'] if os.path.isfile(os.path.join(ROOT, 'package-lock.json')) else ['install'])
    print('[build-hq-ui] building UI bundle (esbuild)…')
    run(['run', 'build'])


def _copy_bundle():
    src = os.path.join(DIST, 'bundle')
    if not os.path.isdir(src):
        raise SystemExit('[build-hq-ui] dist-ui/bundle missing — Node build did not run?')
    shutil.copytree(src, os.path.join(OUT, 'bundle'))
    # Public graph viewer (fixed-name bundle referenced by graph-viewer.html).
    viewer = os.path.join(DIST, 'graph-viewer.js')
    if os.path.isfile(viewer):
        shutil.copy2(viewer, os.path.join(OUT, 'graph-viewer.js'))


def main():
    _run_node_build()

    _force_rmtree(OUT)
    os.makedirs(OUT, exist_ok=True)

    copied = 0
    for f in FILES:
        src = os.path.join(ROOT, f)
        if os.path.isfile(src):
            shutil.copy2(src, os.path.join(OUT, f))
            copied += 1
        else:
            print(f'[build-hq-ui] WARN missing {f}')
    for d in DIRS:
        src = os.path.join(ROOT, d)
        if os.path.isdir(src):
            shutil.copytree(src, os.path.join(OUT, d))
            copied += 1

    _copy_bundle()

    # Bake the <!--HQ_SCRIPTS--> placeholder in the COPIED hq.html from the build
    # manifest (vendor globals + app scripts, content-hashed).
    manifest = ui_manifest.load_manifest(DIST)
    hq_html_path = os.path.join(OUT, 'hq.html')
    with open(hq_html_path, encoding='utf-8') as fh:
        html = fh.read()
    with open(hq_html_path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(ui_manifest.inject(html, manifest))

    with open(os.path.join(OUT, '.ic-assets.json5'), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(IC_ASSETS)

    # IC custom-domain mapping. Serving this canister from hq-ui.cafreso.com makes
    # the post-login iframe SAME-SITE with the API (hq.cafreso.com) and the shell
    # (ai.cafreso.com) — all under cafreso.com — so the hq_session cookie is
    # first-party and never dropped by third-party-cookie blocking. Mirrors
    # frontend/static/.well-known/ic-domains.
    well_known = os.path.join(OUT, '.well-known')
    os.makedirs(well_known, exist_ok=True)
    with open(os.path.join(well_known, 'ic-domains'), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('hq-ui.cafreso.com\n')

    print(f'[build-hq-ui] wrote {copied} entries + bundle/ (+ .well-known/ic-domains) -> {OUT}')


if __name__ == '__main__':
    main()
