#!/usr/bin/env python3
"""Assemble the `hq-ui/` asset-canister build dir for the CafresoHQ frontend.

The HQ app (hq.html + *.jsx + styles.css + assets + sw.js + manifest) is normally
served by serve.py. For the frontend/backend split it's served from an ICP asset
canister instead (1-min `dfx deploy`, fleet-wide, no image rebuild). This script
copies ONLY the UI files into `hq-ui/` (so serve.py, oci-fleet, node_modules, etc.
never ship to the canister) and writes the canister's `.ic-assets.json5`
(cache + CSP). It is the `build` step of the `cafresohq_ui` canister in dfx.json.

Cross-platform (Windows/WSL/Linux); pure stdlib. Idempotent — wipes and rebuilds.
"""
import os
import stat
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, 'hq-ui')

# Files copied verbatim from the repo root.
FILES = [
    'hq.html', 'styles.css', 'sw.js', 'manifest.webmanifest',
    'tweaks-panel.jsx', 'sprites.jsx', 'claude-client.jsx', 'mock-data.jsx',
    'ui.jsx', 'modals.jsx', 'features.jsx', 'views.jsx', 'missions.jsx',
    'agent_runner.jsx', 'app.jsx',
]
DIRS = ['assets']

# Canister upload config. The HQ app loads React/Babel/xterm from unpkg and fonts
# from Google, transpiles JSX in-browser ('unsafe-inline' + 'wasm-unsafe-eval'),
# and calls the container API + terminal WebSocket cross-origin. connect-src is
# permissive for https/wss so the API origin (Caddy/container) and ws endpoints
# work; tighten to your exact API origin in production if desired.
IC_ASSETS = r'''// Auto-generated by scripts/build_hq_ui.py — do not edit by hand.
[
  {
    match: "**/*",
    headers: {
      "Cache-Control": "public, max-age=600",
      "X-Content-Type-Options": "nosniff",
      "Referrer-Policy": "strict-origin-when-cross-origin",
      "Content-Security-Policy": "default-src 'self'; img-src 'self' data: blob: https:; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https: wss: http://localhost:* http://127.0.0.1:* ws://localhost:* ws://127.0.0.1:*; frame-src 'self' https://identity.ic0.app https://*.cafreso.com; frame-ancestors 'self' https://*.cafreso.com; form-action 'self';"
    }
  },
  {
    match: "hq.html",
    headers: { "Cache-Control": "public, max-age=0, must-revalidate" }
  },
  {
    match: "sw.js",
    headers: { "Cache-Control": "public, max-age=0, must-revalidate" }
  }
]
'''


def _force_rmtree(path):
    """rmtree that survives Windows read-only attributes (copy2 preserves the
    read-only bit from source assets, which makes a plain rmtree fail WinError 5)."""
    def _on_err(func, p, _exc):
        try:
            os.chmod(p, stat.S_IWRITE)
            func(p)
        except Exception:
            pass
    if not os.path.isdir(path):
        return
    try:                                   # Python 3.12+: onexc
        shutil.rmtree(path, onexc=_on_err)
    except TypeError:                      # older: onerror
        shutil.rmtree(path, onerror=_on_err)


def main():
    _force_rmtree(OUT)
    os.makedirs(OUT, exist_ok=True)

    copied = 0
    for f in FILES:
        src = os.path.join(ROOT, f)
        if os.path.isfile(src):
            shutil.copy2(src, os.path.join(OUT, f))
            copied += 1
        else:
            print(f'[build-hq-ui] WARN missing {f}')
    for d in DIRS:
        src = os.path.join(ROOT, d)
        if os.path.isdir(src):
            shutil.copytree(src, os.path.join(OUT, d))
            copied += 1

    with open(os.path.join(OUT, '.ic-assets.json5'), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(IC_ASSETS)

    print(f'[build-hq-ui] wrote {copied} entries -> {OUT}')


if __name__ == '__main__':
    main()
